<a href="https://colab.research.google.com/github/RogerUltimate/-Keras-study---project/blob/main/%EB%94%B0%EB%A6%89%EC%9D%B4_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn import tree
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Keras study/따릉이 예측/train.csv')
test = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Keras study/따릉이 예측/test.csv')
submission = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Keras study/따릉이 예측/submission.csv')

In [ ]:
train.interpolate(inplace=True)
test.interpolate(inplace=True)

In [ ]:
feature_cols = ['hour', 'hour_bef_temperature','hour_bef_windspeed','hour_bef_ozone']
label_cols = ['count']

feature_df = pd.DataFrame(train, columns=feature_cols)
label_df = pd.DataFrame(train, columns=label_cols)
x_train = feature_df.to_numpy()
y_train = label_df.to_numpy()

test_df = pd.DataFrame(test, columns=feature_cols)
x_test = test_df.to_numpy()

In [ ]:
x_train

array([[2.00e+01, 1.63e+01, 1.50e+00, 2.70e-02],
       [1.30e+01, 2.01e+01, 1.40e+00, 4.20e-02],
       [6.00e+00, 1.39e+01, 7.00e-01, 3.30e-02],
       ...,
       [5.00e+00, 1.83e+01, 1.90e+00, 9.00e-03],
       [2.10e+01, 2.07e+01, 3.70e+00, 8.20e-02],
       [1.70e+01, 2.11e+01, 3.10e+00, 4.60e-02]])

In [ ]:
y_train

array([[ 49.],
       [159.],
       [ 26.],
       ...,
       [ 22.],
       [216.],
       [170.]])

In [ ]:
clf = tree.DecisionTreeClassifier(max_depth=4,        
                                  min_samples_split=2,  
                                  min_samples_leaf=2).fit(x_train, y_train.ravel()) 

In [ ]:
pred = clf.predict(x_test)

In [ ]:
pred

array([ 37., 213., 113.,  37., 114.,  95., 213., 213.,  37.,  95., 213.,
       213., 113.,  24., 213., 113.,  15., 213., 213., 113., 213.,  37.,
        15., 113., 113.,  95.,  15.,  95.,  95., 113.,  46.,  15.,  46.,
       113., 213.,  37., 113., 213., 213.,  37.,  46.,  95.,  95.,  95.,
       213., 213.,  37.,  46.,  15.,  46., 213.,  46.,  95., 213., 113.,
        95.,  24., 113.,  15.,  15.,  37.,  95., 213., 213., 213., 213.,
        15., 213., 213.,  15.,  95.,  24.,  95.,  15., 213., 113.,  37.,
       213., 213.,  15., 213., 113.,  37.,  46.,  95., 213.,  46., 113.,
        46., 213., 213., 113.,  46.,  95.,  24.,  46.,  37.,  15., 213.,
       213.,  15., 213.,  46.,  95.,  37., 114.,  95.,  15., 113., 213.,
       213., 213., 213.,  95.,  46., 113., 213.,  24., 113.,  15.,  95.,
        95., 213., 213.,  20.,  95.,  46.,  15., 113.,  46., 113., 113.,
        15., 113., 213., 113.,  20., 113., 213., 213.,  95.,  15.,  37.,
        46.,  46.,  95., 213.,  95., 113., 113., 11

In [ ]:
submission['count'] = pred

In [ ]:
submission1 = submission
submission1

id  count
0       0   37.0
1       1  213.0
2       2  113.0
3       4   37.0
4       5  114.0
..    ...    ...
710  2148   46.0
711  2149   46.0
712  2165   95.0
713  2166  213.0
714  2177   95.0

[715 rows x 2 columns]

In [ ]:
submission1.to_csv('test1.csv', index=False)

In [ ]:
model = GaussianNB()
model.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/naive_bayes.py:206: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
predicted = model.predict(x_test)

In [ ]:
predicted 

array([ 95., 304.,  98.,  95., 144., 108., 402., 227.,  95., 212., 244.,
       142., 142.,  90., 131., 227.,  20., 278., 402., 142., 300.,  19.,
        32.,  92., 132.,  92.,  20., 108.,  95.,  97.,  32.,  90.,  90.,
        92., 278.,  95., 119., 186., 227.,  32.,  94., 116.,  65.,  99.,
       324., 153.,  95.,  90.,  89.,  94., 304.,  94.,  65., 122., 132.,
       212.,  20., 256.,  95.,  18.,  95.,  99., 303., 244., 168., 317.,
        32., 304., 206.,  95., 113.,  26., 212.,  18., 317., 246.,  15.,
       274., 284.,  28., 256., 142.,  15.,  90.,  59., 280.,  90.,  97.,
        50., 219., 317., 168.,  30., 168.,  30.,  69.,  95.,  28., 221.,
       183.,  18., 304.,  27.,  95.,  95., 145.,  92.,  28., 227., 131.,
       227., 284., 183., 113.,  69., 164., 153.,  30., 142.,  20.,  92.,
        95., 219., 122.,  95.,  95.,  44.,  16., 151.,  90., 132., 164.,
        89., 164., 142., 132.,  50., 164., 317., 303., 212.,  28.,  18.,
       128.,  90.,  92., 138.,  95., 161., 227., 16

In [ ]:
submission['count'] = predicted 

In [ ]:
submission2 = submission
submission2

id  count
0       0   95.0
1       1  304.0
2       2   98.0
3       4   95.0
4       5  144.0
..    ...    ...
710  2148   90.0
711  2149   69.0
712  2165   95.0
713  2166  114.0
714  2177   95.0

[715 rows x 2 columns]

In [ ]:
submission2.to_csv('test2.csv', index=False)

In [ ]:
rf_param_grid ={ 
    'n_estimators' : [100, 110, 120],
    'min_samples_leaf' : [1, 2, 3],
    'min_samples_split' : [2, 3, 4]
    }

In [ ]:
rf_clf = RandomForestClassifier() 
grid = GridSearchCV(rf_clf, param_grid = rf_param_grid, scoring='accuracy', n_jobs=1)
rf_clf.fit(x_train, y_train)
rf_pred = rf_clf.predict(x_test)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


In [ ]:
submission['count'] = rf_pred 

In [ ]:
submission3 = submission
submission3

id  count
0       0   26.0
1       1  215.0
2       2   83.0
3       4   18.0
4       5  120.0
..    ...    ...
710  2148   80.0
711  2149   98.0
712  2165  108.0
713  2166  132.0
714  2177  129.0

[715 rows x 2 columns]

In [ ]:
submission3.to_csv('test3.csv', index=False)

In [ ]:
voting_model = VotingClassifier(estimators=[
    ('Decision_Tree', clf), ('Gaussuan', model), ('Random', rf_clf)], 
    weights=[1,1,1], voting='hard')
voting_model.fit(x_train, y_train) 
hard_voting_predicted = voting_model.predict(x_test)


/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:235: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/preprocessing/_label.py:268: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
submission['count'] = hard_voting_predicted

In [ ]:
submission4 = submission
submission4

id  count
0       0   37.0
1       1  213.0
2       2   83.0
3       4   33.0
4       5  114.0
..    ...    ...
710  2148   46.0
711  2149   69.0
712  2165   95.0
713  2166  114.0
714  2177   95.0

[715 rows x 2 columns]

In [ ]:
submission4.to_csv('test4.csv', index=False)